spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:mariadb://localhost:3306/profile?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: profile
      client-secret: password
server:
  port: 8191

logging:
  level:
    org:
      hibernate:
        type: trace